### ISSUE TITLE
Not functional

### ISSUE THREAD

**Issue by gunar** [sigsrv/wfapi#2]
Hi, sigsrv. Thank you *very much* for the code so far.
I'm anxious for this Workflowy API!

To this point, it is not functional yet, right? I tried to run it but I get:

```
Traceback (most recent call last):
  File "C:\Code\wfapi\setup.py", line 7, in <module>
    import wfapi
  File "C:\Code\wfapi\wfapi\__init__.py", line 25, in <module>
    from .workflowy import Workflowy
  File "C:\Code\wfapi\wfapi\workflowy\__init__.py", line 14, in <module>
    from .internal import get_globals_from_home
  File "C:\Code\wfapi\wfapi\workflowy\internal.py", line 5, in <module>
    SCRIPT_TAG_REGEX = re.compile("".join([
NameError: name 're' is not defined
```

Thanks a bunch!

PS: I didn't know how else to contact you :stuck_out_tongue:

**Comment by jrk** [comment]
Same bug for me on `Python 3.3.5 :: Anaconda 2.1.0 (x86_64)` (OS X 10.10)
